Upgrade kubebuilder version + New Alert Manager Config CRD
AmiditeX/mimir-operator pull request #22
Opened 2024-04-04 12:11 UTC by gign0766

Upgrade kubebuilder version from v3 to v4
Add new CRD (mimiralertmanagerconfig) to handle gitops on alert manager configuration for a tenant

2024-04-09 20:14 UTC, AmiditeX requested changes
Thank you for this great PR, I made a few comments for things that need changes. I'll make a test image of this to test on our internal monitoring stack and release an RC following the tests.

2024-04-09 20:14 UTC, eiTi3Aishieg commented on Dockerfile
> -RUN curl -fLo mimirtool https://github.com/grafana/mimir/releases/latest/download/mimirtool-linux-amd64 && \
No more mimirtool in the Docker Image?

2024-04-09 20:14 UTC, eiTi3Aishieg commented on README.md
Please add a line here in the description about the new functionality you are introducing (namely the AlertManagerConfig capabilities)

2024-04-09 20:14 UTC, eiTi3Aishieg commented on api/v1alpha1/mimiralertmanagerconfig_types.go
> +// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
Can we remove this?

2024-04-09 20:14 UTC, eiTi3Aishieg commented on api/v1alpha1/mimirrules_types.go
> +// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
Can we remove this?

2024-04-09 20:14 UTC, eiTi3Aishieg commented on config/crd/bases/mimir.randgen.xyz_alertmanagerconfigs.yaml
I think you want this file gone, you have the same one called mimiralertmanagerconfigs
Probably forgot to remove it after renaming the CRD?

2024-04-09 20:14 UTC, eiTi3Aishieg commented on config/samples/kustomization.yaml
> +  - _v1alpha1_mimiralertmanagerconfig.yaml
The actual file added is called _v1alpha1_alertmanagerconfig.yaml
I think you need to rename that file

2024-04-09 20:14 UTC, eiTi3Aishieg commented on deploy/helm/mimir-operator/crds/mimir.randgen.xyz_alertmanagerconfigs.yaml
Duplicate of an already existing file but named with a "mimir" as a prefix? You probably renamed the CRD and forgot this file.

2024-04-09 20:14 UTC, eiTi3Aishieg commented on deploy/helm/mimir-operator/templates/rbac.yaml
> +  name: { { include "mimir-operator.fullname" . } }
might want to remove those

2024-04-09 20:14 UTC, AmiditeX commented on deploy/helm/mimir-operator/templates/rbac.yaml
> +  name: { { include "mimir-operator.fullname" . } }
same

2024-04-09 20:14 UTC, AmiditeX commented on deploy/helm/mimir-operator/templates/rbac.yaml
> +    name: { { include "mimir-operator.fullname" . } }
same

2024-04-09 20:14 UTC, AmiditeX commented on deploy/helm/mimir-operator/templates/rbac.yaml
> +    namespace: { { .Release.Namespace } }
same

2024-04-09 20:14 UTC, AmiditeX commented on deploy/helm/mimir-operator/templates/rbac.yaml
> +  name: { { include "mimir-operator.fullname" . } }
same

2024-04-09 20:14 UTC, AmiditeX commented on docs/index.md
> +The MimirAlertManagerConfig CRD allows the remote control of the Alert Manager Config for a specific tenant in a Mimir from Kubernetes.
The MimirAlertManagerConfig CRD allows the remote control of the Alertmanager config for a specific tenant in a Mimir **instance** from Kubernetes.

2024-04-09 20:14 UTC, AmiditeX commented on docs/index.md
> +The MimirAlertManagerConfig CRD allows the remote control of the Alert Manager Config for a specific tenant in a Mimir from Kubernetes.
might be clearer

2024-04-09 20:14 UTC, AmiditeX commented on docs/index.md
> +This example shows how to install a MimirAlertManagerConfig to configure a teams webhook into the Alert Manager:
a Teams webhook into the Alertmanager

2024-04-09 20:14 UTC, AmiditeX commented on internal/controller/mimiralertmanagerconfig/mimiralertmanagerconfig.go
> +// func (r *MimirAlertManagerConfigReconciler) configToString(config *domain.MimirAlertManagerConfig) (string, error) {
remove dead code

2024-04-09 20:14 UTC, AmiditeX commented on internal/controller/mimiralertmanagerconfig/mimiralertmanagerconfig_controller.go
> +	// config, err := r.configToString(amc)
dead code

2024-04-10 08:25 UTC, gign0766 commented
Thank for the feedback on my PR.
I have just pushed the requested modifications.

2024-04-10 08:26 UTC, gign0766 commented on Dockerfile
> -RUN curl -fLo mimirtool https://github.com/grafana/mimir/releases/latest/download/mimirtool-linux-amd64 && \
It was a mistake and I've added it back.

2024-04-10 08:37 UTC, AmiditeX reviewed
LGTM, will merge in a separate branch to test CI before going to main

2024-04-10 08:40 UTC, AmiditeX approved these changes

2024-04-10 08:40 UTC, merged